Custom_User_Model/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("",RedirectView.as_view(url="index")),
    path("index/",views.index,name ="index"),
    path("login/", views.login_page, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", LogoutView.as_view(), name='logout'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import ( BaseUserManager, AbstractBaseUser)
from django.contrib.auth.models import UserManager

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user
    admin = models.BooleanField(default=False) # a superuser

    # notice the absence of a "Password field", that is built in.
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # Email & Password are required by default.

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.forms import fields

User = get_user_model()

class LoginForm(forms.Form):
    email = forms.CharField(label='email')
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    """
    The default

    """

    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean_email(self):
        '''
        Verify email is available.
        '''
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")

        '''

        Here you can add further validations on email

        '''

        return email

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ['email', 'password', 'is_active', 'admin']

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, get_user_model
from .forms import *
from django.utils.http import is_safe_url


def index(request):
    return render(request,"index.html")

User = get_user_model()
def signup(request):
    form = RegisterForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        print(form.cleaned_data)
        # username  = form.cleaned_data.get("username")
        email  = form.cleaned_data.get("email")
        password  = form.cleaned_data.get("password")
        new_user  = User.objects.create_user(email, password)
        print(new_user)
        return redirect("/")

    return render(request, "signup.html", context)



def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        "form": form
    }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None
    if form.is_valid():
        print(form)
        email  = form.cleaned_data.get("email")
        password  = form.cleaned_data.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)

            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                return redirect("/")
        else:
            # Return an 'invalid login' error message.
            print("Error")
    return render(request, "login.html", context)

templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
  <!-- Meta Tags -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/gvsslogo.jpeg' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/gvsslogo.jpeg' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/gvsslogo.jpeg' %}">

  <!-- Page Title -->
  <title>GVSS</title>
  <!-- Favicon and Touch Icons -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!-- Stylesheet -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/css-plugin-collections.css' %}" rel="stylesheet" />
  <!-- CSS | megamenu skins -->
  <link href="{% static 'css/navbarmenu.css' %}" rel="stylesheet" />
  <link id="menuzord-menu-skins" href="{% static 'css/rounded-boxed.css' %}" rel="stylesheet" />
  <!-- CSS | Main style file -->
  <link href="{% static 'css/style-main.css' %}" rel="stylesheet" type="text/css">
  <!-- CSS | Custom Margin Padding Collection -->
  <link href="{% static 'css/custom-bootstrap-margin-padding.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/iec-style.css' %}" rel="stylesheet" type="text/css">
  <!-- CSS | Theme Color-->
  <link href="{% static 'css/custom-color.css' %}" rel="stylesheet" type="text/css">
  <!-- CSS | Responsive media queries -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/meri.css' %}" rel="stylesheet" type="text/css">
  <!-- external javascripts -->
  <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- JS | jquery plugin collection for this theme -->
  <script src="{% static 'js/jquery-plugin-collection.js' %}"></script>
</head>


<body id="no-scroll" class="has-fixed-footer">

    <header>

      <div class="container">
        <div class="row">

          <div class="col-12 col-md-8 title-left">
            <div class="logoAnimation-wrapper">
              <h3 class="ar-fontfamily">Django User Login BoilerPlate</h3>
              <h3 class="ar-fontfamily">BY. Chetan45s</h3>
            </div>
          </div>

          <div class="col-sm-12 col-md-4">
            <div class="col-sm-12 col-md-4">
              <div class="title-right">
                <a href="https://github.com/Chetan45s"><span> Chetan45s </span></a>
                <br>
                <br>
                <br>
              </div>
            </div>
          </div>

        </div>
      </div>

      <div class="mynavbar" id="mynavbar1">
        <nav>
          <ul class="main-list">

            {% if user.is_authenticated %}
              <li class="link"><a href="/logout" class="toggle">Logout</a></li>
            {% else %}
              <li class="link"><a href="/login" class="toggle">Login</a></li>
              <li class="link"><a href="/signup" class="toggle">Sign Up</a></li>
            {% endif %}
          </ul>

        </nav>
      </div>
    </header>
    {% block content %}
    {% endblock %}
    <!-- Footer -->

     <footer id="footer" class="footer" data-bg-color="#212331">
      <div class="container pt-50 pb-15">
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <div class="widget dark">
              <h3 class="text-white text-center mb-10 mt-0">Django User Login BoilerPlate</h3>
              <ul class="list-inline mt-5 text-center">
                <li > <i class="fa fa-envelope-o text-white mr-5"></i>  <a class="text-gray" href="mailto:">chetansalmotra45@gmail.com </a>  </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
  <div class="footer-bottom" data-bg-color="#2b2d3b">
    <div class="container pt-20 pb-20">
          <p class="font-13 text-black-777 m-0 sm-text-center">Copyright © 2021 Chetan45s. All Rights Reserved.
          </p>
    </div>
  </div>
  </footer>

  <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
  </div>
  <script type="text/javascript">
    $(document).ready(function () {
      $(document).mouseup(function (e) {
        if ($(".showhide").css('display') != 'none') {
          var menu = $('.menuzord-menu');
          if (!menu.is(e.target) // The target of the click isn't the container.
            &&
            menu.has(e.target).length === 0) // Nor a child element of the container
          {
            menu.slideUp();
          }
        }
      });
    });
    $(window).load(function () {
      var heights = $(".owl-item .item article .entry-content").map(function () {
        return $(this).height();
      }).get();
      maxHeight = Math.max.apply(null, heights);
      $(".owl-item .item article .entry-content").height(maxHeight);
    });
  </script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('.megamenu.megamenu-bg-img').removeClass('nv');
    });
  </script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/announcement.js' %}"></script>
  <script src="{% static 'js/meri.js' %}"></script>
  <script>
    $(window).load(function (e) {
      $("#bn1").breakingNews({
        effect: "slide-h",
        autoplay: true,
        timer: 5000,
        color: "red"
      });
    });
  </script>
</body>
</html>

templates/index.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}

  <section class="bg-silver-deep">
    <div class="container pb-40 ar-container-pad">
      <div class="section-title">

        <div class="row">

          <div class="col-md-7 pricing-table">
          
              <h2 class="text-uppercase font-weight-600 mt-0 mt-sm-30 title events-main"> <span class="text-theme-colored2">Current </span>Features </h2>
              <p>Adding Something</p>
            <div class="double-line-bottom-theme-colored-2"></div>
          </div>

          <div class="col-md-5">

            <h2 class="text-uppercase font-weight-600 mt-0 mt-sm-30 title events-main"> <span class="text-theme-colored2">Upcoming </span>Features </h2>
            <div class="double-line-bottom-theme-colored-2"></div>

          </div>

        </div>
      </div>
    </div>
  </section>



</div>
  <script>
    var slideIndex = 0;
    showSlides();
    function showSlides() {
      var i;
      var slides = document.getElementsByClassName("mySlides0");
      var dots = document.getElementsByClassName("dot0");
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      slideIndex++;
      if (slideIndex > slides.length) {
        slideIndex = 1
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active0", "");
      }
      slides[slideIndex - 1].style.display = "block";
      dots[slideIndex - 1].className += " active0";
      setTimeout(showSlides, 5000); // Change image every 2 seconds
    }
  </script>
{% endblock %}

templates/login.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>GVSS</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Normalize CSS -->
    <link rel="stylesheet" href="{% static 'css11/normalize.css' %}">
    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'css11/main.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css11/bootstrap.min.css' %}">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="{% static 'css11/all.min.css' %}">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="{% static 'fonts11/flaticon.css' %}">
    <!-- Full Calender CSS -->
    <link rel="stylesheet" href="{% static 'css11/fullcalendar.min.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'css11/animate.min.css' %}">
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="{% static 'css11/jquery.dataTables.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css11/style.css' %}">
    <!-- Modernize js -->
    <script src="{% static 'js11/modernizr-3.6.0.min.js' %}"></script>
</head>

<body>

    <div class="login-page-wrap">
        <div class="login-page-content">
            <div class="login-box">

                <form method="post" class="login-form">
                {% csrf_token %}


                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input type="text" name="email" required id="id_email" placeholder="Enter usrename" class="form-control">
                        <i class="far fa-envelope"></i>
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input type="password" name="password" required id="id_password" placeholder="Enter password" class="form-control">
                        <i class="fas fa-lock"></i>
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="remember-me">
                            <label for="remember-me" class="form-check-label">Remember Me</label>
                        </div>
                        <a href="#" class="forgot-btn">Forgot Password?</a>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="login-btn">Login</button>
                    </div>
                    <a href="{% url 'signup' %}" class="forgot-btn">Don't Have Account?</a>
                </form>
            </div>
        </div>
    </div>
    <!-- Login Page End Here -->
    <!-- jquery-->
    <script src="{% static 'js11/jquery-3.3.1.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js11/plugins.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js11/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js11/bootstrap.min.js' %}"></script>
    <!-- Scroll Up Js -->
    <script src="{% static 'js11/jquery.scrollUp.min.js' %}"></script>
    <!-- Custom Js -->
    <script src="{% static 'js11/main.js' %}"></script>

</body>

</html>

templates/signup.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>GVSS</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/gvsslogo.jpeg' %}">
    <!-- Normalize CSS -->
    <link rel="stylesheet" href="{% static 'css11/normalize.css' %}">
    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'css11/main.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css11/bootstrap.min.css' %}">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="{% static 'css11/all.min.css' %}">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="{% static 'fonts11/flaticon.css' %}">
    <!-- Full Calender CSS -->
    <link rel="stylesheet" href="{% static 'css11/fullcalendar.min.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'css11/animate.min.css' %}">
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="{% static 'css11/jquery.dataTables.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css11/style.css' %}">
    <!-- Modernize js -->
    <script src="{% static 'js11/modernizr-3.6.0.min.js' %}"></script>
</head>

<body>

    <div class="login-page-wrap">
        <div class="login-page-content">
            <div class="login-box">

                <form method="post" class="login-form">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        {{ form.email.errors }}
                        <label for="id_email">Email</label>
                        <input type="email" name="email" maxlength="255" required id="id_email" placeholder="Enter Email" class="form-control">
                        <i class="far fa-envelope"></i>
                    </div>

                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input  type="password" name="password" required id="id_password" placeholder="Enter password" class="form-control">
                        <i class="fas fa-lock"></i>
                    </div>
                    <div class="form-group">
                        <label for="id_password_2">Confirm Password</label>
                        <input type="password" name="password_2" required id="id_password_2" placeholder="Enter password" class="form-control">
                        <i class="fas fa-lock"></i>
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between">
                        <div class="form-check">

                        </div>
                        <a href="#" class="forgot-btn">Forgot Password?</a>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="login-btn">Sign Up</button>
                    </div>
                    <a href="{% url 'login' %}" class="forgot-btn">Already Have Account?</a>

                </form>
            </div>
        </div>
    </div>
    <!-- Login Page End Here -->
    <!-- jquery-->
    <script src="{% static 'js11/jquery-3.3.1.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js11/plugins.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js11/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js11/bootstrap.min.js' %}"></script>
    <!-- Scroll Up Js -->
    <script src="{% static 'js11/jquery.scrollUp.min.js' %}"></script>
    <!-- Custom Js -->
    <script src="{% static 'js11/main.js' %}"></script>

</body>

</html>